---
title: "Cover Letter"
---

Dear Hiring Manager,

I am writing to express my interest in the Data Architect Analyst position. I have experience working with data management and dashboard development, and I believe I would be a great fit for the role.

Although I have minimal experience with **Power BI and Access Database** I have experience building dashboards from scratch with Shiny. I am also confident in my ability to quickly adapt and learn new skills. I have extensive experience cleaning and organizing large datasets to make sure they are accurate and useful. I enjoy working with data and figuring out ways to improve processes through better organization and reporting.

In my past role, I’ve collaborated with different teams to understand their data needs and deliver insights that drive improvements. I also have experience with **SQL, Python, and R**, which have helped me analyze data more effectively and automate tasks.

I would love the chance to talk more about how I can contribute to the team.

Thank you for your time and consideration.

Best,

Grey Gergen\
